// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

uniform Texture2D<float4> _TextureA;
uniform Texture2D<float4> _TextureB;
uniform RWStructuredBuffer<int> _Counter;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float dif = abs(_TextureA[id.xy] - _TextureB[id.xy]);
    InterlockedAdd(_Counter[0], floor(10 * (1.0 - dif)));
}
