// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

uniform Texture2D<float4> _TextureA;
uniform Texture2D<float4> _TextureB;
uniform StructuredBuffer<int> _Counter;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float r = (dot(_TextureA[id.xy], _TextureB[id.xy]) + 1.0) * 0.5;
    int v = 10 * r;
    int g;
    InterlockedAdd(_Counter[0], v, g);
}
